### ISSUE TITLE
National Park suggestions

### ISSUE THREAD

**Issue by KittJonathan** [kevinsblake/NatParksPalettes#1]
Hi there ! Thanks for this fantastic package ! Would it be possible to add some parks from the UK, such as the Cairgorms, the Trossachs, the Lake District ? I can look into it if that can be of any help.

**Comment by kevinsblake** [comment]
Thanks for the suggestions! Yes, I already have the next version in the works and am making a point to include NPs from outside North America. I'll be sure to check those out.

**Comment by kevinsblake** [comment]
Added South Downs National Park, UK.
