### ISSUE TITLE
Cross-reference package

### ISSUE THREAD

**Issue by statzhero** [kevinsblake/NatParksPalettes#2]
NatParksPalettes package is different from [this package](https://github.com/katiejolly/nationalparkcolors), correct?

**Comment by kevinsblake** [comment]
Correct, different packages. Nationalparkcolors has beautiful palettes. But my goals with this package were to base palettes on photography instead of WPA posters, and include additional functions like colorblind friendliness check and ggplot compatibility.

**Comment by statzhero** [comment]
Amazing work, thank you!
